forge "https://forge.puppetlabs.com"

mod 'jfryman/nginx'
mod 'thomasvandoren/redis'
mod 'puppetlabs/vcsrepo'
mod 'puppetlabs/firewall'
mod 'stankevich/puppet-python',
    :git => "https://github.com/stankevich/puppet-python.git"

mod 'marvelous_nginx', :path => './custom_modules/marvelous_nginx'
mod 'marvelous_packages', :path => './custom_modules/marvelous_packages'
mod 'marvelous_website', :path => './custom_modules/marvelous_website'
