forge "https://forge.puppetlabs.com"

mod 'jfryman/nginx'
mod 'thomasvandoren/redis'
mod 'puppetlabs/vcsrepo'

mod 'marvelous_nginx', :path => './custom_modules/marvelous_nginx'
mod 'marvelous_packages', :path => './custom_modules/marvelous_packages'
